### ISSUE TITLE
Request timeout

### ISSUE THREAD

**Issue by brunowindrop** [InstagramScraperAPI/php-sdk#1]
Hello, unfortunately the api is not working, it is returning the following error. can you help me?

[02-Jan-2022 20:38:22 America/New_York] PHP Fatal error:  Uncaught InstagramScraperAPI\Exception: Request timeout. in /home/infludados/public_html/influ/vendor/instagramscraperapi/php-sdk/src/InstagramScraper.php:311
Stack trace:
#0 /home/infludados/public_html/influ/index.php(14): InstagramScraperAPI\InstagramScraper->searchUsers('nik')
#1 {main}
  thrown in /home/infludados/public_html/influ/vendor/instagramscraperapi/php-sdk/src/InstagramScraper.php on line 311

**Comment by angeljunior** [comment]
As Instagram updates its protection and defense policies, we have evolved the system in search of new servers and proxy routing via residential and mobile, at times it may have an error as well.
